service: vollaWebMainNuxt

provider:
  name: aws
  apiName: ${opt:stage, 'dev'}-rsfiveVollaWebmainNuxt
  endpointType: regional
  role: arn:aws:iam::771405576262:role/VollaLambdaExecutor
  runtime: nodejs10.x
  memorySize: 512
  timeout: 12

  region: ap-northeast-2

  environment: # 환경 변수
    STAGE: ${opt:stage, 'dev'}
    NODE_ENV: ${opt:node_env, 'development'}
  deploymentBucket:
    name: com.riversouthfive.volla.${self:provider.region}.deploys
    tags:
      stage: ${self:provider.stage}
      api-name: ${self:provider.apiName}

tracing:
  lambda: true
  apiGateway: true

plugins:
  - serverless-offline
  - serverless-domain-manager
  - serverless-apigw-binary
  # - serverless-plugin-warmup

package:
  excludeDevDependencies: true
  exclude:
    - .**
    - .**/*
    - pages/**
    - components/**
    - store/**
    - assets/**
    - layouts/**
    - plugins/**
    - test/**
    - middleware/**
    - README.md
    - package.json
    - package-lock.json
    - node_modules/**/*.md
    - node_modules/**/bin/**
    - node_modules/**

  include:
    - server/**
    - config/index.js
    - config/config.js
    - nuxt.config.js
    - .nuxt/**
    # - node_modules/autoprefixer/**
    # - node_modules/babel-runtime/**
    # - node_modules/babel-extract-comments/**

layers:
  webmainNuxt:
    path: layers
    name: ${self:provider.stage}-sls-webmain-nuxt-nodemodules
    compatibleRuntimes:
      - nodejs10.x
    description: node_module folder
    package:
      excludeDevDependencies: true

functions:
  render:
    handler: server/handler.render # server/handler.js의 render 함수를 가리킴
    layers:
      - { Ref: WebmainNuxtLambdaLayer }
    events:
      - http:
          path: '/'
          method: get
      - http:
          path: '{proxy+}'
          method: get

custom:
  apigwBinary:
    types:
      - '*/*'
  customDomain:
    domainName: '${self:provider.stage}-sls-webpage.volla.live'
    stage: ${self:provider.stage}
    basePath:
    createRoute53Record: true
    certificateName: '*.volla.live'
    endpointType: 'regional'
